#!/bin/bash

sudo -v # ask for password only at the beginning


#install homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"


#configure homebrew
sudo brew update
sudo brew upgrade
sudo brew tap homebrew/versions
sudo brew tap phinze/homebrew-cask


#install cli apps
sudo brew install coreutils
sudo brew install git
sudo brew install vim
sudo brew install mackup
sudo brew install zsh

#install gui apps (with cask)
sudo brew cask install dropbox
sudo brew cask install firefox
sudo brew cask install flash
sudo brew cask install google-chrome
sudo brew cask install firefox
sudo brew cask install google-drive
sudo brew cask install hipchat
sudo brew cask install node
sudo brew cask install sequel-pro
sudo brew cask install sublime-text
sudo brew cask install harvest
sudo brew cask install vagrant
sudo brew cask install virtualbox
sudo brew cask install bee
sudo brew cask install transmit
sudo brew cask install inc
sudo brew cask install adobe-creative-cloud
sudo brew cask install mongohub
sudo brew cask install sonos
sudo brew cask install spotify
sudo brew cask install slack
sudo brew cask install mailbox
sudo brew cask install vlc

#custom quicklooks
sudo brew cask install qlcolorcode
sudo brew cask install qlstephen
sudo brew cask install qlmarkdown
sudo brew cask install quicklook-json
sudo brew cask install qlprettypatch
sudo brew cask install quicklook-csv
sudo brew cask install betterzipql
sudo brew cask install webp-quicklook
sudo brew cask install suspicious-package

#link sublime for global 'sublime' command
ln -s /Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl /usr/local/bin/sublime


#install vagrant-cachier (to speed up provisioning)
sudo vagrant plugin install vagrant-hostmanager
sudo npm install -g yeoman

sudo npm install -g francisbond/generator-francis-craft
sudo gem install sass
sudo gem install hologram

