#!/bin/bash

sudo -v # ask for password only at the beginning


#install homebrew
ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"


#configure homebrew
brew update
brew upgrade
brew tap homebrew/versions
brew tap phinze/homebrew-cask


#install cli apps
brew install coreutils
brew install git
brew install vim
brew install mackup
brew install zsh

#install gui apps (with cask)
brew cask install dropbox
brew cask install firefox
brew cask install flash
brew cask install google-chrome
brew cask install firefox
brew cask install google-drive
brew cask install hipchat
brew cask install node
brew cask install sequel-pro
brew cask install sublime-text
brew cask install harvest
brew cask install vagrant
brew cask install virtualbox
brew cask install bee
brew cask install transmit
brew cask install inc
brew cask install adobe-creative-cloud
brew cask install mongohub



#custom quicklooks
brew cask install qlcolorcode
brew cask install qlstephen
brew cask install qlmarkdown
brew cask install quicklook-json
brew cask install qlprettypatch
brew cask install quicklook-csv
brew cask install betterzipql
brew cask install webp-quicklook
brew cask install suspicious-package

#link sublime for global 'sublime' command
ln -s /Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl /usr/local/bin/sublime


#install vagrant-cachier (to speed up provisioning)
vagrant plugin install vagrant-cachier
