#!/bin/bash

sudo -v # ask for password only at the beginning


#install homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"


#configure homebrew
sudo brew update
sudo brew upgrade
sudo brew tap homebrew/versions
sudo brew tap phinze/homebrew-cask


#install cli apps
sudo brew install coreutils
sudo brew install git
sudo brew install vim
sudo brew install mackup
sudo brew install zsh

#install gui apps (with cask)
sudo brew cask install dropbox
sudo brew cask install firefox
sudo brew cask install flash
sudo brew cask install google-chrome
sudo brew cask install google-drive
sudo brew cask install slack
sudo brew cask install node
sudo brew cask install sublime-text
sudo brew cask install vagrant
sudo brew cask install virtualbox
sudo brew cask install adobe-creative-cloud
sudo brew cask install spotify
sudo brew cask install vlc
sudo brew cask install flux
sudo brew cask install divvy
sudo brew cask install sonos
sudo brew cask install chromecast
sudo brew cask install garmin-express
sudo brew cask install gopro-studio
sudo brew cask install skype
sudo brew cask install iterm2






#custom quicklooks
sudo brew cask install quicklook-csv
sudo brew cask install betterzipql
sudo brew cask install webp-quicklook
sudo brew cask install suspicious-package

#link sublime for global 'sublime' command
ln -s /Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl /usr/local/bin/sublime


#install vagrant-cachier (to speed up provisioning)
sudo vagrant plugin install vagrant-hostmanager
sudo npm i -g yo bower gulp

sudo npm install -g angusfretwell/generator-craftsman


